### ISSUE TITLE
请问提示一下该怎么解决

### ISSUE THREAD

**Issue by axiliya2568** [lktlktlkt/ticket-damai#7]
在控制台输入pip install -r requirements.txt -i https://pypi.douban.com/simple后提示
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl
.c:998)'))': /simple/apscheduler/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl
.c:998)'))': /simple/apscheduler/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl
.c:998)'))': /simple/apscheduler/
ERROR: Could not find a version that satisfies the requirement APScheduler==3.9.1 (from versions: none)
ERROR: No matching distribution found for APScheduler==3.9.1
该怎么解决，python是3.9版本

**Comment by lktlktlkt** [comment]
那就不指定依赖模块的版本，安装python环境自适应的模块版本。或者试试APScheduler==3.10.1

**Comment by axiliya2568** [comment]
请问大佬能封装成exe吗，那样可能使用起来更简单

**Comment by axiliya2568** [comment]
PS D:\桌面\ticket-damai-main> pip install -r requirements.txt -i https://pypi.douban.com/simple
Looking in indexes: https://pypi.douban.com/simple
Requirement already satisfied: APScheduler==3.9.1 in c:\python311\lib\site-packages (from -r requirements.txt (line 1)) (3.9.1)
Requirement already satisfied: loguru==0.6.0 in c:\python311\lib\site-packages (from -r requirements.txt (line 2)) (0.6.0)
Requirement already satisfied: PyYAML==6.0 in c:\python311\lib\site-packages (from -r requirements.txt (line 3)) (6.0)
Requirement already satisfied: requests==2.27.1 in c:\python311\lib\site-packages (from -r requirements.txt (line 4)) (2.27.1)
Requirement already satisfied: future~=0.18.2 in c:\python311\lib\site-packages (from -r requirements.txt (line 5)) (0.18.3)
Requirement already satisfied: aiohttp~=3.8.1 in c:\python311\lib\site-packages (from -r requirements.txt (line 6)) (3.8.4)
Requirement already satisfied: setuptools>=0.7 in c:\python311\lib\site-packages (from APScheduler==3.9.1->-r requirements.txt (line 1)) (58.1.0)
Requirement already satisfied: six>=1.4.0 in c:\python311\lib\site-packages (from APScheduler==3.9.1->-r requirements.txt (line 1)) (1.16.0)
Requirement already satisfied: pytz in c:\python311\lib\site-packages (from APScheduler==3.9.1->-r requirements.txt (line 1)) (2023.3)
Requirement already satisfied: tzlocal!=3.*,>=2.0 in c:\python311\lib\site-packages (from APScheduler==3.9.1->-r requirements.txt (line 1)) (5.0.1)
Requirement already satisfied: colorama>=0.3.4 in c:\python311\lib\site-packages (from loguru==0.6.0->-r requirements.txt (line 2)) (0.4.6)
Requirement already satisfied: win32-setctime>=1.0.0 in c:\python311\lib\site-packages (from loguru==0.6.0->-r requirements.txt (line 2)) (1.1.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\python311\lib\site-packages (from requests==2.27.1->-r requirements.txt (line 4)) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\python311\lib\site-packages (from requests==2.27.1->-r requirements.txt (line 4)) (2023.5.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\python311\lib\site-packages (from requests==2.27.1->-r requirements.txt (line 4)) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in c:\python311\lib\site-packages (from requests==2.27.1->-r requirements.txt (line 4)) (3.4)
Requirement already satisfied: attrs>=17.3.0 in c:\python311\lib\site-packages (from aiohttp~=3.8.1->-r requirements.txt (line 6)) (23.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\python311\lib\site-packages (from aiohttp~=3.8.1->-r requirements.txt (line 6)) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\python311\lib\site-packages (from aiohttp~=3.8.1->-r requirements.txt (line 6)) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\python311\lib\site-packages (from aiohttp~=3.8.1->-r requirements.txt (line 6)) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in c:\python311\lib\site-packages (from aiohttp~=3.8.1->-r requirements.txt (line 6)) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in c:\python311\lib\site-packages (from aiohttp~=3.8.1->-r requirements.txt (line 6)) (1.3.1)
Requirement already satisfied: tzdata in c:\python311\lib\site-packages (from tzlocal!=3.*,>=2.0->APScheduler==3.9.1->-r requirements.txt (line 1)) (2023.3)
大佬我终端现在安装成这样，然后运行run.py
提示下面这个是为啥啊 C:\Users\vcc\Scripts\python.exe D:/桌面/ticket-damai-main/run.py 
Traceback (most recent call last):
  File "D:\桌面\ticket-damai-main\run.py", line 1, in <module>
    from damai import Runner
  File "D:\桌面\ticket-damai-main\damai\__init__.py", line 20, in <module>
    from damai.engine import ExecutionEngine
  File "D:\桌面\ticket-damai-main\damai\engine.py", line 3, in <module>
    from damai.orderview import OrderView
  File "D:\桌面\ticket-damai-main\damai\orderview.py", line 6, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'
我这应该已经把loguru安装好了吧
进程已结束,退出代码1

**Comment by axiliya2568** [comment]
大佬前面的我解决了

**Comment by axiliya2568** [comment]
新出现的C:\Users\vcc\Scripts\python.exe C:/ticket-damai-main/example/cookie.py 
Traceback (most recent call last):
  File "C:\ticket-damai-main\example\cookie.py", line 16, in <module>
    asyncio.run(make_cookie())
  File "D:\python\anaconda\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\python\anaconda\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\ticket-damai-main\example\cookie.py", line 10, in make_cookie
    instant.update_default_config(Configs())
  File "C:\ticket-damai-main\damai\performer.py", line 62, in update_default_config
    raise ValueError(f"{self}需要配置COOKIE")
ValueError: <damai.performer.ApiFetchPerform object at 0x000001FBAD3BCDC0>需要配置COOKIE
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001FBAE0371F0>这个报错是什么意思

**Comment by axiliya2568** [comment]
大佬这个配置一次后是不是以后只要换场次的cookie和商品id就可以了

**Comment by axiliya2568** [comment]
然后这个能抢票吗，我看还没开售的用这个就卡在场次价格数量，是等开售会自己响应吗

**Comment by axiliya2568** [comment]
> 是的 先试试正常开售的能否购买 cookie有时效性

正常开售的能买，那cookie大概多久有效啊

**Comment by lktlktlkt** [comment]
由你请求频率决定 最多不会超过半小时就会失效

**Comment by axiliya2568** [comment]
> 由你请求频率决定 最多不会超过半小时就会失效

那如果是捡漏的话，我大概半小时要换一次对吧

**Comment by lktlktlkt** [comment]
可以自己测试下

**Comment by axiliya2568** [comment]
> 

好的，谢谢

**Comment by zazoCoder** [comment]
main\damai\performer.py", line 62, in update_default_config raise ValueError(f"{self}需要配置COOKIE") ValueError: <damai.performer.ApiFetchPerform object at 0x000001FBAD3BCDC0>需要配置COOKIE Unclosed client session client_session: <aiohttp.client.ClientSession object at 0x000001FBAE0371F0>
您好   这个问题我还没解决  应该怎么处理呢

**Comment by lktlktlkt** [comment]
> main\damai\performer.py", line 62, in update_default_config raise ValueError(f"{self}需要配置COOKIE") ValueError: <damai.performer.ApiFetchPerform object at 0x000001FBAD3BCDC0>需要配置COOKIE Unclosed client session client_session: <aiohttp.client.ClientSession object at 0x000001FBAE0371F0> 您好 这个问题我还没解决 应该怎么处理呢
运行时，先配置cookie，这是一个必填项。

**Comment by axiliya2568** [comment]
> > main\damai\performer.py", line 62, in update_default_config raise ValueError(f"{self}需要配置COOKIE") ValueError: <damai.performer.ApiFetchPerform object at 0x000001FBAD3BCDC0>需要配置COOKIE Unclosed client session client_session: <aiohttp.client.ClientSession object at 0x000001FBAE0371F0> 您好 这个问题我还没解决 应该怎么处理呢
> > 运行时，先配置cookie，这是一个必填项。

大佬运行一分钟就提示这个是为什么
AttributeError: 'NoneType' object has no attribute 'get'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001C784F0F250>然后就停止运行了

**Comment by lktlktlkt** [comment]
> > > main\damai\performer.py", line 62, in update_default_config raise ValueError(f"{self}需要配置COOKIE") ValueError: <damai.performer.ApiFetchPerform object at 0x000001FBAD3BCDC0>需要配置COOKIE Unclosed client session client_session: <aiohttp.client.ClientSession object at 0x000001FBAE0371F0> 您好 这个问题我还没解决 应该怎么处理呢
> > > 运行时，先配置cookie，这是一个必填项。
> 
> 大佬运行一分钟就提示这个是为什么 AttributeError: 'NoneType' object has no attribute 'get' Unclosed client session client_session: <aiohttp.client.ClientSession object at 0x000001C784F0F250>然后就停止运行了

报错详细呢

**Comment by axiliya2568** [comment]
> > > > main\damai\performer.py", line 62, in update_default_config raise ValueError(f"{self}需要配置COOKIE") ValueError: <damai.performer.ApiFetchPerform object at 0x000001FBAD3BCDC0>需要配置COOKIE Unclosed client session client_session: <aiohttp.client.ClientSession object at 0x000001FBAE0371F0> 您好 这个问题我还没解决 应该怎么处理呢
> > > > 运行时，先配置cookie，这是一个必填项。
> > 
> > 
> > 大佬运行一分钟就提示这个是为什么 AttributeError: 'NoneType' object has no attribute 'get' Unclosed client session client_session: <aiohttp.client.ClientSession object at 0x000001C784F0F250>然后就停止运行了
> 
> 报错详细呢

client_session: <aiohttp.client. ClientSession object at 0x000001C784F0F250>还有这个，但我重启下软件就又可以运行很久了，不知道是为啥，还有个问题，大佬每次运行都要重新启动example.cookie吗，还是之间再yaml里面改就行

**Comment by lihua123987** [comment]
> 新出现的C:\Users\vcc\Scripts\python.exe C:/ticket-damai-main/example/cookie.py Traceback (most recent call last): File "C:\ticket-damai-main\example\cookie.py", line 16, in asyncio.run(make_cookie()) File "D:\python\anaconda\lib\asyncio\runners.py", line 44, in run return loop.run_until_complete(main) File "D:\python\anaconda\lib\asyncio\base_events.py", line 647, in run_until_complete return future.result() File "C:\ticket-damai-main\example\cookie.py", line 10, in make_cookie instant.update_default_config(Configs()) File "C:\ticket-damai-main\damai\performer.py", line 62, in update_default_config raise ValueError(f"{self}需要配置COOKIE") ValueError: <damai.performer.ApiFetchPerform object at 0x000001FBAD3BCDC0>需要配置COOKIE Unclosed client session client_session: <aiohttp.client.ClientSession object at 0x000001FBAE0371F0>这个报错是什么意思

请问下cookie的配置格式，大佬给删了，我现在想用

**Comment by axiliya2568** [comment]
> > 新出现的C:\Users\vcc\Scripts\python.exe C:/ticket-damai-main/example/cookie.py Traceback (most recent call last): File "C:\ticket-damai-main\example\cookie.py", line 16, in asyncio.run(make_cookie()) File "D:\python\anaconda\lib\asyncio\runners.py", line 44, in run return loop.run_until_complete(main) File "D:\python\anaconda\lib\asyncio\base_events.py", line 647, in run_until_complete return future.result() File "C:\ticket-damai-main\example\cookie.py", line 10, in make_cookie instant.update_default_config(Configs()) File "C:\ticket-damai-main\damai\performer.py", line 62, in update_default_config raise ValueError(f"{self}需要配置COOKIE") ValueError: <damai.performer.ApiFetchPerform object at 0x000001FBAD3BCDC0>需要配置COOKIE Unclosed client session client_session: <aiohttp.client.ClientSession object at 0x000001FBAE0371F0>这个报错是什么意思
> 
> 请问下cookie的配置格式，大佬给删了，我现在想用

已经不能用了所以删了

**Comment by lktlktlkt** [comment]
之前获取cookie的方式依然可用

**Comment by axiliya2568** [comment]
> 之前获取cookie的方式依然可用

![99_Q(QLUIVQUCA@`9AD~9@B](https://github.com/lktlktlkt/ticket-damai/assets/139161227/724019e3-a5a8-4f3f-b114-879580931eaf)
请问下为什么我重新配置的cookie还是提示哎呦喂被挤爆了，网站上是有票的

**Comment by lktlktlkt** [comment]
按之前的方式 多尝试几次

**Comment by axiliya2568** [comment]
> 按之前的方式 多尝试几次

 也就是说现在出现这种情况是正常的吗，只要多试试就行吗

**Comment by axiliya2568** [comment]
> 按之前的方式 多尝试几次

多换几次cookie吗

**Comment by fj0203** [comment]
> > 按之前的方式 多尝试几次
> 
> 多换几次cookie吗

开售有盾的，抢不到的
